## CHRUN DATA

#### Loading the dataset

In [2]:
import pandas as pd
import numpy as np

In [4]:
path = r"C:\Users\aparn\OneDrive\Desktop\mlops_project\Data\CC_MLOps_project\Machine_Learning_MLOPS_Project\Machine_Learning_MLOPS_Project\artifacts\raw\raw.csv"
df = pd.read_csv(path)
df.shape

(92, 31)

In [5]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    92 non-null     int64
 1   V1      92 non-null     float64
 2   V2      92 non-null     float64
 3   V3      92 non-null     float64
 4   V4      92 non-null     float64
 5   V5      92 non-null     float64
 6   V6      92 non-null     float64
 7   V7      92 non-null     float64
 8   V8      92 non-null     float64
 9   V9      92 non-null     float64
 10  V10     92 non-null     float64
 11  V11     92 non-null     float64
 12  V12     92 non-null     float64
 13  V13     92 non-null     float64
 14  V14     92 non-null     float64
 15  V15     92 non-null     float64
 16  V16     92 non-null     float64
 17  V17     92 non-null     float64
 18  V18     92 non-null     float64
 19  V19     92 non-null     float64
 20  V20     92 non-null     float64
 21  V21     92 non-null     float64
 22  V22     92 non-null     float64
 23  V23     92 non-null     float64
 24  V24     92 non-null     float64
 25  V25     92 non-null     float64
 26  V26     92 non-null     float64
 27  V27     92 non-null     float64
 28  V28     92 non-null     float64
 29  Amount  92 non-null     float64
 30  Class   92 non-null     int64
dtypes: float64(29), int64(2)
memory usage: 22.4 KB

In [8]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,92.000000,92.000000,92.000000,92.000000,92.000000,92.000000,92.000000,92.000000,92.000000,92.000000,...,92.000000,92.000000,92.000000,92.000000,92.000000,92.000000,92.000000,92.000000,92.000000,92.0
mean,31.608696,-0.121130,0.111011,0.872308,0.395872,0.089017,0.344987,0.166153,-0.009485,-0.053488,...,-0.002033,-0.015059,-0.000559,0.096556,0.133501,-0.047787,0.017783,0.007308,68.287609,0.0
std,16.542291,1.333159,1.155578,0.852078,1.278697,1.342909,1.324706,0.842210,0.698950,0.825098,...,0.414389,0.518798,0.413401,0.550958,0.405378,0.525269,0.304298,0.260072,192.050646,0.0
min,0.000000,-5.401258,-5.450148,-0.932038,-4.515824,-6.631951,-1.763406,-2.705393,-3.807864,-2.094011,...,-0.852309,-1.299920,-1.134769,-1.384620,-1.112725,-1.243924,-1.206921,-1.105751,0.750000,0.0
25%,18.000000,-0.859570,-0.117434,0.280026,-0.240323,-0.450083,-0.400678,-0.122310,-0.194421,-0.438674,...,-0.198160,-0.314634,-0.157224,-0.118761,-0.033149,-0.337241,-0.049463,-0.001925,6.140000,0.0
50%,34.000000,-0.314901,0.251327,0.853925,0.569076,-0.024977,0.029714,0.222756,0.083157,-0.111557,...,-0.050299,-0.008182,-0.067120,0.104251,0.155116,-0.213096,0.026799,0.022828,18.115000,0.0
75%,44.500000,1.110739,0.645313,1.356785,1.216294,0.419191,0.352283,0.568728,0.253520,0.264297,...,0.047593,0.235959,0.057979,0.403862,0.395186,0.169298,0.121138,0.099957,45.982500,0.0
max,60.000000,1.492936,2.600138,3.402585,3.710061,3.281972,5.122103,4.371691,1.530817,4.009259,...,1.943465,1.353650,2.458589,1.112970,0.820591,3.065576,0.857373,0.949594,1402.950000,0.0